/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103x6.h"
#include "stm32f103x6_gpio_driver.h"
#include "stm32f103x6_USART_driver.h"
#include "keyPad.h"
#include "lcd.h"
#include "PIR.h"
#include "Servo_Motor.h"
#include "alarm.h"
#include "Timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define No_ALLOWED_IDS    3
#define true         1
#define false        0

uint8_t is_id_exists(uint8_t id);
void handle_entrance_request();
void handle_exit_request();
void operate_parking_gate(uint8_t gate_number);

Lcd_Config lcd1, lcd2;
uint8_t allowed_ids[No_ALLOWED_IDS];

uint8_t empty_slots = 3;

#define RED_ALARM_PIN    GPIO_PIN_0
#define GREEN_ALARM_PIN  GPIO_PIN_11

#define PIR1_PIN  		 GPIO_PIN_7
#define PIR2_PIN  		 GPIO_PIN_1

#define ENTRANCE_GATE    0
#define EXIT_GATE  		 1

void LCD_Print_Welcome_Msg();
void LCD_Print_Entrance_Msg();
void LCD_Print_ValidID_Msg(uint8_t gate);
void LCD_Print_WrongID_Msg();
int main(void)
{
	RCC_GPIOA_ENABLE();
	RCC_GPIOB_ENABLE();

	Timer2_init();

	lcd2.CTRL_Gpio = GPIOB;
	lcd2.DATA_Gpio = GPIOB;
	lcd2.EN = GPIO_PIN_10;
	lcd2.RS = GPIO_PIN_11;
	lcd2.D4 = GPIO_PIN_12;
	lcd2.D5 = GPIO_PIN_13;
	lcd2.D6 = GPIO_PIN_14;
	lcd2.D7 = GPIO_PIN_15;

	lcd1.CTRL_Gpio = GPIOA;
	lcd1.DATA_Gpio = GPIOA;
	lcd1.RS = GPIO_PIN_5;
	lcd1.EN = GPIO_PIN_6;
	lcd1.D4 = GPIO_PIN_12;
	lcd1.D5 = GPIO_PIN_13;
	lcd1.D6 = GPIO_PIN_14;
	lcd1.D7 = GPIO_PIN_15;

	PIR_init(GPIOA, PIR1_PIN);
	PIR_init(GPIOA, PIR2_PIN);

	Servo1_Entry_Gate_Init();
	Servo2_Exit_Gate_Init();

	alarm_init(GPIOA, RED_ALARM_PIN);
	alarm_init(GPIOA, GREEN_ALARM_PIN);

	LCD_init(&lcd1);
	LCD_init(&lcd2);
	Keypad_init();

	LCD_writeString(&lcd2, "Enter Allowed ID");
	LCD_goTo_X_and_Y(&lcd2, LCD_SECOND_ROW, LCD_COL_4);
	LCD_writeString(&lcd2, "First  ID:");
	allowed_ids[0] = Keypad_getkey();
	LCD_writeChar(&lcd2, allowed_ids[0]);

	LCD_goTo_X_and_Y(&lcd2, LCD_THIRD_ROW, LCD_COL_4);
	LCD_writeString(&lcd2, "Second ID:");
	allowed_ids[1] = Keypad_getkey();
	LCD_writeChar(&lcd2, allowed_ids[1]);

	LCD_goTo_X_and_Y(&lcd2, LCD_FOURTH_ROW, LCD_COL_4);
	LCD_writeString(&lcd2, "Third  ID:");
	allowed_ids[2] = Keypad_getkey();
	LCD_writeChar(&lcd2, allowed_ids[2]);

	LCD_clearDisplay(&lcd2);
	LCD_writeString(&lcd2, "IDS are Saved");
	LCD_goTo_X_and_Y(&lcd2, LCD_SECOND_ROW, LCD_COL_0);

	int i;
	for(i=0; i<No_ALLOWED_IDS; i++)
	{
		LCD_writeChar(&lcd2, allowed_ids[i]);
		LCD_writeChar(&lcd2, ' ');
	}

	LCD_Print_Welcome_Msg();
	LCD_Print_Entrance_Msg();

	USART_config config;
	config.Baud_Rate = USART_Baude_Rate_115200;
	config.Data_Length = USART_Frame_Length_8;
	config.HW_FlowControl = USART_HW_FC_disable;
	config.Interrupt_Enable = USART_Received_data_ready;
	config.Parity = USART_Frame_parity_DISABLE;
	config.Stop_Bits = USART_Frame_StopBit_one;
	config.USART_MODE = USART_MODE_RX_TX;
	config.p_callback = handle_entrance_request;
	MCAL_USART_Init(USART1, &config);
	MCAL_USART_GPIO_Set_Pins(USART1);

	config.p_callback = handle_exit_request;
	MCAL_USART_Init(USART2, &config);
	MCAL_USART_GPIO_Set_Pins(USART2);

	while(1)
	{
		__asm("wfe");
	}
}

void handle_entrance_request()
{
	uint8_t entrance_id;
	MCAL_USART_RX(USART1, (uint16_t*)&entrance_id, 1, Interrupt);
	if(empty_slots > 0)
	{
		if(is_id_exists(entrance_id) == true)
		{
			LCD_Print_ValidID_Msg(ENTRANCE_GATE);
			empty_slots--;
			alarm_start(GPIOA, GREEN_ALARM_PIN);
			operate_parking_gate(ENTRANCE_GATE);
		}else {
			LCD_Print_WrongID_Msg();
			alarm_start(GPIOA, RED_ALARM_PIN);
		}
	}else {
		LCD_Print_Entrance_Msg();
		alarm_start(GPIOA, RED_ALARM_PIN);
	}
	LCD_Print_Welcome_Msg();
	LCD_Print_Entrance_Msg();
}

void handle_exit_request()
{
	uint8_t exit_id;
	MCAL_USART_RX(USART2, (uint16_t*)&exit_id, 1, Interrupt);

	if(is_id_exists(exit_id) == true)
	{
		LCD_Print_ValidID_Msg(EXIT_GATE);
		empty_slots++;
		alarm_start(GPIOA, GREEN_ALARM_PIN);
		operate_parking_gate(EXIT_GATE);
	}else {
		LCD_Print_WrongID_Msg();
		alarm_start(GPIOA, RED_ALARM_PIN);
	}

	LCD_Print_Welcome_Msg();
	LCD_Print_Entrance_Msg();
}

void operate_parking_gate(uint8_t gate)
{
	if(gate == ENTRANCE_GATE)
	{
		Servo1_Entry_Gate(UP);
		dms(400);
		while(PIR_is_Car_Detected(GPIOA, PIR1_PIN) == 1);
		Servo1_Entry_Gate(Down);
	}else if(gate == EXIT_GATE)
	{
		Servo2_Exit_Gate(UP);
		while(PIR_is_Car_Detected(GPIOA, PIR2_PIN) == 1);
		Servo2_Exit_Gate(Down);
	}

}

uint8_t is_id_exists(uint8_t id)
{
	int i=0;
	for(i=0; i < No_ALLOWED_IDS; i++)
	{
		if(id == allowed_ids[i]){
			return true;
		}
	}
	return false;
}

void LCD_Print_Welcome_Msg()
{
	LCD_clearDisplay(&lcd1);
	LCD_writeString(&lcd1, "Welcome in");
	LCD_goTo_X_and_Y(&lcd1, LCD_SECOND_ROW, LCD_COL_0);
	LCD_writeString(&lcd1, "Car Parking");
}

void LCD_Print_ValidID_Msg(uint8_t gate)
{
	LCD_clearDisplay(&lcd1);
	LCD_writeString(&lcd1, "ID Is Right");
	LCD_goTo_X_and_Y(&lcd1, LCD_SECOND_ROW, LCD_COL_0);
	if(gate == ENTRANCE_GATE){
		LCD_writeString(&lcd1, "Entry Gate Opens");
	}else {
		LCD_writeString(&lcd1, "Exit Gate Opens");
	}
}

void LCD_Print_WrongID_Msg()
{
	LCD_clearDisplay(&lcd1);
	LCD_writeString(&lcd1, "Wrong ID");
	LCD_goTo_X_and_Y(&lcd1, LCD_SECOND_ROW, LCD_COL_0);
	LCD_writeString(&lcd1, "Try Again");
}

void LCD_Print_Entrance_Msg()
{
	if(empty_slots > 0)
	{
		LCD_clearDisplay(&lcd1);
		LCD_writeString(&lcd1, "Empty Slots ");
		LCD_writeChar(&lcd1, empty_slots+'0');
		LCD_goTo_X_and_Y(&lcd1, LCD_THIRD_ROW, LCD_COL_0);
		LCD_writeString(&lcd1, "Put Your Id In");
		LCD_goTo_X_and_Y(&lcd1, LCD_FOURTH_ROW, LCD_COL_0);
		LCD_writeString(&lcd1, "Card Reader");
	}else {
		LCD_clearDisplay(&lcd1);
		LCD_writeString(&lcd1, "Empty Slot = 0");
		LCD_clearDisplay(&lcd1);
		LCD_writeString(&lcd1, "Parking is Full");
		LCD_goTo_X_and_Y(&lcd1, LCD_SECOND_ROW, LCD_COL_0);
		LCD_writeString(&lcd1, "Entry is Not");
		LCD_goTo_X_and_Y(&lcd1, LCD_THIRD_ROW, LCD_COL_0);
		LCD_writeString(&lcd1, "Allowed");
	}
}
