/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6_gpio_driver.h"
#include "stm32f103x6.h"

void wait();

int main(void)
{


	RCC_GPIOA_ENABLE();
	RCC_GPIOB_ENABLE();

	GPIO_Pin_Config conigPin;

	conigPin.Pin_Mode = Floating_Input;
	conigPin.Pin_Number = GPIO_PIN_1;
	MCAL_GPIO_Init(GPIOA, &conigPin);

	conigPin.Pin_Mode = Floating_Input;
	conigPin.Pin_Number = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOA, &conigPin);

	conigPin.Pin_Mode = General_Purpose_Output_PP;
	conigPin.Pin_Number = GPIO_PIN_1;
	conigPin.Pin_Speed = GPIO_Pin_Max_Speed10M;
	MCAL_GPIO_Init(GPIOB, &conigPin);

	conigPin.Pin_Mode = General_Purpose_Output_PP;
	conigPin.Pin_Number = GPIO_PIN_13;
	conigPin.Pin_Speed = GPIO_Pin_Max_Speed10M;
	MCAL_GPIO_Init(GPIOB, &conigPin);


	while(1)
	{
		if (MCAL_GPIO_Read_Pin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET)
		{
			MCAL_GPIO_Toggle_Pin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_Read_Pin(GPIOA, GPIO_PIN_1) == GPIO_PIN_RESET);
		}
		if (MCAL_GPIO_Read_Pin(GPIOA, GPIO_PIN_13) == GPIO_PIN_SET)
		{
			MCAL_GPIO_Toggle_Pin(GPIOB, GPIO_PIN_13);
		}
		wait();

	}
}

void wait()
{
	for(int i =0; i<10000; i++);
}
