/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../HAL/Inc/lcd.h"
#include "../HAL/Inc/keyPad.h"
#include "stm32f103x6_gpio_driver.h"
#include "stm32f103x6.h"
#include "stm32f103x6_EXTI_driver.h"
#include "stm32f103x6_PWM_driver.h"
#include "../HAL/Inc/servo.h"

void clock_init();
int main(void)
{
	clock_init();

	Servo_Config servo1;
	servo1.TIM = TIM2;
	servo1.TIM_channel = TIM_CHANNEL3;
	servo1.curr_angle = 0;

	HAL_Servo_Init(&servo1);

	while(1){
		for(int i=0; i<=180; i++){
			HAL_Servo_Write(&servo1, i);
			for(int j=0; j<=1800; j++);
		}
		for(int j=0; j<=1800000; j++);
		for(int i=180; i >= 0; i--){
			HAL_Servo_Write(&servo1, i);
			for(int j=0; j<=1800; j++);
		}
		for(int j=0; j<=1800000; j++);
	}
}

void clock_init(){
	RCC_GPIOA_ENABLE();
	RCC_GPIOB_ENABLE();
	RCC_TIM2_ENABLE();
}


