/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../HAL/Inc/lcd.h"
#include "../HAL/Inc/keyPad.h"

void clock_init();
int main(void)
{
	clock_init();
	LCD_init();
	Keypad_init();
	//LCD_writeString("hello world");
	//LCD_backClearDisplay();

    /* Loop forever */
	for(;;){
		unsigned char g = Keypad_getkey();
		if(g != '!')
			LCD_writeChar(g);

	}
}

void clock_init(){
	RCC_GPIOA_ENABLE();
	RCC_GPIOB_ENABLE();
}
